[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ajay Kumar Singh", email = "ajay.singh@questionpro.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "piccolo[all]>=1.36.0",
    "ruff>=0.16.7",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"
